#!/bin/sh

if [ -x "$(command -v pygmentize)" ]; then
  case "$1" in
      *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
      *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
      *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
      *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass|*.pp|*.yml|*.md|*.json|Makefile|*.erb|Rakefile)
          pygmentize -O style=native,bg=dark "$1";;
      .bashrc|.bash_aliases|.bash_environment)
          pygmentize -l sh "$1"
          ;;
      *)
          grep "#\!.*bash" "$1" > /dev/null
          if [ "$?" -eq "0" ]; then
              pygmentize -l sh "$1"
          else
              exit 1
          fi
  esac
fi

exit 0
